#ec2 version
#version: 0.0
#os: linux
#files:
#  - source: ./Dockerfile
#    destination: /webservice
#  - source: ./target
#    destination: /webservice
#  - source: ./build_expose.sh
#    destination: /webservice
#file_exists_behavior: OVERWRITE
##  - source: Config/config.txt
##    destination: /webapps/Config
##  - source: source
##    destination: /webapps/myApp
#hooks:
##  BeforeInstall:
##    - location: Scripts/UnzipResourceBundle.sh
##    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: build_expose.sh
#      timeout: 3600
#      runas: root
##  ApplicationStart:
##    - location: build_expose.sh
##      timeout: 3600
##      runas: root
##  ValidateService:
##    - location: Scripts/MonitorService.sh
##      timeout: 3600
##      runas: codedeployuser



####ecs version
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "th-request-api"
          ContainerPort: 8080